### ISSUE TITLE
4.2 Share Profiles Feature Start : 15/03/23 End : 28/03/23

### ISSUE THREAD

**Issue by DoubleBounce** [JustBrandonLim/ICT2106_P2_Project_M1#127]
This item will be updated whenever there are additions to anything pertaining to the Share Profiles Feature

**Comment by DoubleBounce** [comment]
Starting on this feature.

**Comment by Lavenzaa** [comment]
Static Landing page done for shared platform.
User should be able to view more details of each profile shown on the platform and be able to use it.


![Image](https://user-images.githubusercontent.com/94179890/224553571-5fcd7e4f-759a-4e9e-bc5f-7123846d49f9.png)


![Image](https://user-images.githubusercontent.com/94179890/224553601-6f734dc9-0bff-4a12-967f-9e8c155a6ba8.png)



![Image](https://user-images.githubusercontent.com/94179890/224553618-4bd756a0-be47-4a47-980b-fddceb4dac95.png)

**Comment by DoubleBounce** [comment]
Tested and runs as expected. Will be closing this issue now.
