### ISSUE TITLE
3.2.7.5 Team Member's Reflection: Norman Chia

### ISSUE THREAD

**Issue by pangkaho14** [JustBrandonLim/ICT2106_P2_Project_M1#141]

**Comment by ncmj1998** [comment]
9.3 Norman Chia
During my experience implementing the decorator pattern, I’ve realised how critical it is to choose the right design pattern for a system. The decorator pattern allows for flexible composition of objects with different properties, while also adhering to the Single Responsibility and Open-Closed principles of the SOLID principle. This experience has significantly changed the way I approach software design in the future. 

Going forward, I plan to prioritise following the SOLID principles when designing software by selecting the most appropriate design patterns for the components in my system. Doing so will enable scalability and maintainability, ultimately leading to improved software quality, cost savings, and time efficiency. I recognize that there may be potential drawbacks to design patterns as well, so I will be sure to consider these factors and evaluate trade-offs accordingly. Overall, I’m excited to apply what I’ve learned from the decorator pattern to my future software projects and continue to grow as a software developer.

If I were given another opportunity to work on this project, I would utilise the knowledge and skills I have gained to create a more effective and efficient software design. Specifically, I would prioritise following the SOLID principles to create a scalable and maintainable codebase that can adapt to future changes. This approach would not only improve the quality of the software but also help me to develop a skil lset that would be valuable in my  future career.
