### ISSUE TITLE
Add Adapter Design Pattern for D2

### ISSUE THREAD

**Issue by JustBrandonLim** [JustBrandonLim/ICT2106_P2_Project_M1#147]
As discussed with the team, we have decided to implement the adapter design pattern into our code base, particularly with the two methods `GetDevicePossibleConfigurationsAsync` and `GetDeviceConfigurationsAsync`.

This should allow the frontend to use the data much easier, as the backend will handle all the transformation of data.

**Comment by JustBrandonLim** [comment]
![Image](https://user-images.githubusercontent.com/93673724/225440086-5f21a8b2-d4a7-4db3-914e-6a4f0abead7f.png)

This adapter allows us to transform this data from the DB,

![Image](https://user-images.githubusercontent.com/93673724/225440252-56c74b6d-eee1-4694-9c00-1ce18e1dfd42.png)


to this:

![Image](https://user-images.githubusercontent.com/93673724/225440402-8f46dc7c-abc6-4ffe-a675-b3eaa21d401d.png)

and this,

![Image](https://user-images.githubusercontent.com/93673724/225440596-b8952ed6-352b-4819-a4c5-0f029afb1efb.png)

to this:

![Image](https://user-images.githubusercontent.com/93673724/225440779-e0217e22-b7fe-48e7-8bb7-8d42d7c8bee3.png)


As the frontend is written in React, passing data via JSON would be ideal as JSON is supported in JavaScript by default. This allows the frontend developers to easily map the data for display.

**Comment by bran-donut** [comment]
Integrated the Adapter Design Pattern into the Manage Configurations Feature

Data is passed via JSON through the adapter and handled by handleDeviceConfigurations to update configurations upon change through the POST request.

![Image](https://user-images.githubusercontent.com/90169441/225579597-253efb59-c96a-4676-83a6-04b5eca00493.png)
