### ISSUE TITLE
4.5 Client Demo 2 Start: 28/03/23 | End: 28/03/23

### ISSUE THREAD

**Issue by personryan** [JustBrandonLim/ICT2106_P2_Project_M1#174]
This section encompasses what each member did during the client Demo

**Comment by Lavenzaa** [comment]
Presented on Share Profile and Parental Controls Features



![Image](https://user-images.githubusercontent.com/94179890/228454386-de763d5c-8fca-4e90-9cd7-ba630c0c2e8b.png)


![Image](https://user-images.githubusercontent.com/94179890/228454477-1875c836-4abf-46bd-bd76-70bdf136df97.png)

**Comment by Lth323** [comment]
Q&A: Responsible for the clarification on how the devices are linked to the profiles, and how different settings for devices form a scenario. Which will be added to a particular profile.

**Comment by FS75** [comment]
Q&A: Answered Miss Sahar on her questions about the linkage between scenarios and profiles, also on the difference between the "add scenario" button found in a profile, and the "scenario" navbar item. The conclusion was to implement informational tooltips for users to interact with, to understand the differences between the 2 buttons (there are not much differences, "add scenario" button just redirects users to the scenario page.

What is envisioned is for users to be able to add scenarios from a profile page, and to also add scenarios to a profile from a scenario page

**Comment by DoubleBounce** [comment]
Presented the enabling of 2FA for an account. 



![Image](https://user-images.githubusercontent.com/79396686/229097051-64e53837-009b-4ca5-814a-f28df148f44f.png)



![Image](https://user-images.githubusercontent.com/79396686/229097871-48d4fd9a-edce-44d1-9b58-d0f276864b75.png)



![Image](https://user-images.githubusercontent.com/79396686/229097927-14855784-f392-4ebd-a7f4-c607076e10b7.png)



![Image](https://user-images.githubusercontent.com/79396686/229098045-443a793c-f2a8-409c-aa98-eafce5aabadb.png)
