### ISSUE TITLE
3.1.2 Feature 2: Create 2D Grid Home

### ISSUE THREAD

**Issue by fabianchua6** [JustBrandonLim/ICT2106_P2_Project_M1#34]

**Comment by ShaunVSIT** [comment]
**Progress Update:**

Baseline front end for 2D grid home implemented:

Functionalities implemented so far:

- [X] 1. Add new room
- [X] 2. Delete existing room

![Image](https://user-images.githubusercontent.com/91268180/225581057-e44606bc-7c14-4954-83f3-b172ee8c7370.png)

**Comment by ShaunVSIT** [comment]
Backend Implemented:

- [X] POST and GET for room coordinates
- [X] POST and GET for room devices



![Image](https://user-images.githubusercontent.com/91268180/228247591-926b36df-a47a-4fdd-9d64-a40ce08a7bb9.png)



![Image](https://user-images.githubusercontent.com/91268180/228247741-2644f47c-e532-4ca6-935c-eb1c8c1b208b.png)
