### ISSUE TITLE
3.1.3 Feature 3: Add Device to 2D Grid Home

### ISSUE THREAD

**Issue by fabianchua6** [JustBrandonLim/ICT2106_P2_Project_M1#35]

**Comment by pangkaho14** [comment]
Working on 2DHomeWriteService to add capability to add device to a 2D Grid Home, exploring SOLID principles and other design patterns:


![Image](https://user-images.githubusercontent.com/71180280/222536690-1b2d9b40-1875-4aaf-bc9d-d27121348e2b.png)

**Comment by pangkaho14** [comment]
TODO: Review lecture content and adjust design

Created class at local branch at the moment:


![Image](https://user-images.githubusercontent.com/71180280/222538404-f209d6ae-ba9c-4ddd-8813-1da8eab01b41.png)

**Comment by pangkaho14** [comment]
**Progress update**

- [x] Added TwoDHomeRepository to support database operations for ITwoDHomeRepository.
- [x] Added Factory pattern for requests, responses, room grids, room coordinates and device coordinate to achieve DIP


![Image](https://user-images.githubusercontent.com/71180280/225073948-18e0ca11-654d-497f-b6c2-a6bd8f858abd.png)



![Image](https://user-images.githubusercontent.com/71180280/225073980-bb92808f-64b7-471f-8ab3-4cddba512725.png)




![Image](https://user-images.githubusercontent.com/71180280/225074538-9742a29f-11be-4d78-8848-00a71bc4f4ee.png)

**Comment by pangkaho14** [comment]
Delegated 2DHomeWriteService to @wangqixian15 to expose DB operations to API layer.

**Comment by pangkaho14** [comment]
added front end:

![Image](https://user-images.githubusercontent.com/71180280/227768181-73ebde20-06cc-4f11-b1be-bb4977560f6a.png)



![Image](https://user-images.githubusercontent.com/71180280/227768194-47c94bbb-9b31-48a5-bd40-6cdfbf200c04.png)

**Comment by pangkaho14** [comment]
Closing issue, integration is done with bug fixes.
