### ISSUE TITLE
3.1.4 Feature 4: Manage Devices in 2D Grid Home

### ISSUE THREAD

**Issue by fabianchua6** [JustBrandonLim/ICT2106_P2_Project_M1#36]

**Comment by wangqixian15** [comment]
Work in progress, logic for collision detection between room coordinates completed.


![Image](https://user-images.githubusercontent.com/73416707/224672384-0fb066e5-5eab-4900-941e-f0db27451be4.png)

**Comment by wangqixian15** [comment]
Feature completed and implemented

- [ ] Added AddRoomCoordinate and AddDeviceCoordinate ReadService in the Domain layer
- [ ] Added Interface to expose both Read and Write service for 2D Home
- [ ] Device state change in the front end view.



![Image](https://user-images.githubusercontent.com/73416707/228787842-590cda70-42a6-4a16-af9b-44074287c0b7.png)

![Image](https://user-images.githubusercontent.com/73416707/228788496-f7fae80b-d038-437e-977c-b15fc7c3fc8a.png)

![Image](https://user-images.githubusercontent.com/73416707/228788577-296216c9-026e-4101-a275-0f584e2179e2.png)

![Image](https://user-images.githubusercontent.com/73416707/228789177-6b43293d-5f81-4532-9d2f-154054e0b76d.jpg)
