### ISSUE TITLE
3.1.5 Feature 5: Purchase new devices

### ISSUE THREAD

**Issue by fabianchua6** [JustBrandonLim/ICT2106_P2_Project_M1#37]

**Comment by ncmj1998** [comment]
Front end for device store

![Image](https://user-images.githubusercontent.com/39306724/228419097-ec41a05e-c1a5-4004-80ba-e7be79bfbf26.png)

**Comment by ncmj1998** [comment]
API calls for device store 


![Image](https://user-images.githubusercontent.com/39306724/228419272-921ee33c-4c01-410a-b5a2-2607edecfb16.png)
