### ISSUE TITLE
3.2.3 Team's Component and Class Diagrams

### ISSUE THREAD

**Issue by fabianchua6** [JustBrandonLim/ICT2106_P2_Project_M1#40]

**Comment by pangkaho14** [comment]
Added class diagram for repository classes for 2d home feature

![Image](https://user-images.githubusercontent.com/71180280/228867892-eb5b6684-a8a1-475d-876d-d0e076a1a276.png)

**Comment by fabianchua6** [comment]
added class diagram for room feature including all presentation, domain logic and data source classes

![Image](https://user-images.githubusercontent.com/57614749/228886021-5b010577-2909-4b54-9c04-b7ad080da978.jpeg)
![Image](https://user-images.githubusercontent.com/57614749/228886019-6a5d7c88-d738-47d2-a239-20026791a3d8.jpeg)
![Image](https://user-images.githubusercontent.com/57614749/228886020-7ccd4acc-e398-4763-8cb6-3b09525a6cd2.jpeg)

**Comment by pangkaho14** [comment]
Updated component diagram:



![Image](https://user-images.githubusercontent.com/71180280/228892802-ce543396-b59e-4b08-a5ef-28e74deb586a.png)

**Comment by ShaunVSIT** [comment]
Added class diagram for TwoDHomesController:


![Image](https://user-images.githubusercontent.com/91268180/228901480-586352df-6a62-4aaf-b183-f297ebf6b58d.jpg)

Added class diagram for 2D Grid Home feature including interface, control, DTO and entity classes:


![Image](https://user-images.githubusercontent.com/91268180/228901882-1e9e6ee4-acbc-4979-9bca-5cd6e75d0ae6.jpg)

**Comment by wangqixian15** [comment]
- [ ] Added TwoDHomeReadSerivce and Interface for TwoDHomeReadService.
- [ ] Added Factories for TwoDHome.
- [ ] Added DTOs for Device and Room Coordinates.


![Image](https://user-images.githubusercontent.com/73416707/228913105-7e458395-e5ab-418c-a40f-42cccd5584c9.jpg)
![Image](https://user-images.githubusercontent.com/73416707/228913600-4319750e-2e42-40f5-989a-ac033d0fa006.jpg)
![Image](https://user-images.githubusercontent.com/73416707/228913977-b1989879-b119-43eb-9e13-b8406156f696.jpg)

**Comment by normanchia** [comment]
Added class diagram for Product Store feature to the team's component and class diagram

![Image](https://user-images.githubusercontent.com/39306724/229071095-68a8fd0f-43f0-4a2e-8ffa-1b0f36e9bdc7.jpeg)
![Image](https://user-images.githubusercontent.com/39306724/229071097-fe7c9228-b1c3-448f-b8a9-57f0fd6bc98d.jpeg)
![Image](https://user-images.githubusercontent.com/39306724/229071096-2d4231bf-946b-4048-8fc2-46246171557e.jpeg)

**Comment by pangkaho14** [comment]
All diagrams done
