### ISSUE TITLE
3.2.5 Software Design Patterns

### ISSUE THREAD

**Issue by fabianchua6** [JustBrandonLim/ICT2106_P2_Project_M1#41]

**Comment by ncmj1998** [comment]
6.2 Decorator Design Pattern 
The decorator pattern is used to enhance the behaviour of the product list by decorating it with different pricing options. This allows for the implementation of various pricing strategies, such as seasonal discounts or currency conversions, while keeping the original structure of the product list intact. By utilising the decorator pattern, you can easily add and remove pricing options without affecting the underlying product list, making it a flexible and scalable solution.
6.2.1 Implementation
Figure x.x depicts the class diagram for implementing the Decorator Design Pattern. Figure x.x to x.x illustrates the code implementation.

The ProductDiscountDecorator acts as the abstract decorator class which defines the common functionality of all decorators, including the ability to access the underlying product and apply a discount. The SummerDiscountDecorator is an example of a concrete decorator class that will inherit from ProductDiscountDecorator and apply a discount to the product price. 

This pattern allows for addition of new pricing strategies by creating new concrete decorator classes that inherit from ProductdiscountDecorator and overrides the ApplyDiscount method. This approach provides a way to dynamically modify the behaviour of individual product instances at runtime, without affecting other products or the overall product list structure.

**Comment by pangkaho14** [comment]
Added factory pattern description in report along with SOLID principles with Norman. For more details, please refer to the report on sections 5 and 6.




![Image](https://user-images.githubusercontent.com/71180280/229078598-32ee022c-c60e-4ae5-bac7-bda215b01100.png)



![Image](https://user-images.githubusercontent.com/71180280/229078555-75a1213c-6689-43c2-b8d8-5b31b6a013ff.png)
