### ISSUE TITLE
Implementation for Edit Device Details Page

### ISSUE THREAD

**Issue by bran-donut** [JustBrandonLim/ICT2106_P2_Project_M1#73]
**Description**
This task involves implementing the functionality of the Edit Device Details Page for the Home Smart Manager application. The Edit Device Details Page allows users to manage their edit their device details and settings. 

**Tasks**

- [x] Implement the functionality for the device details page
- [x] Integrate frontend and backend

**Comment by JustBrandonLim** [comment]
Created the following endpoints to enable React to call.



![Image](https://user-images.githubusercontent.com/93673724/223826689-a283c2b9-e4ac-4f42-b7e9-36b8843813c6.png)

**Comment by bran-donut** [comment]
Created frontend device settings page and integrated backend functionalities
 

![Image](https://user-images.githubusercontent.com/90169441/223827595-d765240c-5078-45a2-9928-f4207527096e.png)



![Image](https://user-images.githubusercontent.com/90169441/223827724-ac56bc63-f89e-4969-a833-eaf41eee3129.png)
