### ISSUE TITLE
Implementation for Configurations Page

### ISSUE THREAD

**Issue by bran-donut** [JustBrandonLim/ICT2106_P2_Project_M1#75]
**Description**
This task involves implementing the functionality of the Configurations Page for the Home Smart Manager application. The Configurations Page allows users to manage their device settings and preferences, such as customizing the behavior of their smart devices. 

**Tasks**

- [x] Implement the functionality for the configurations page
- [x] Integrate frontend and backend

**Comment by bran-donut** [comment]
Implemented functionality for the configurations page 
Integrated backend to frontend code for the configurations page 

![Image](https://user-images.githubusercontent.com/90169441/223829125-12e530c8-9dbe-4658-a5c5-21031bb87e6f.png)


![Image](https://user-images.githubusercontent.com/90169441/223829220-c8540226-f3bc-44eb-8c4b-1ba0bcb17474.png)


![Image](https://user-images.githubusercontent.com/90169441/223829286-557edcf2-e120-45a6-9a11-d4fbba0b6526.png)

**Comment by JustBrandonLim** [comment]
![Image](https://user-images.githubusercontent.com/93673724/223935738-4b033fff-1b12-4bb8-bd08-4466297dca0e.png)

Implemented these APIs to enable frontend integration.
