### ISSUE TITLE
Implementation for Password lock for configuration settings

### ISSUE THREAD

**Issue by bran-donut** [JustBrandonLim/ICT2106_P2_Project_M1#79]

**Comment by p1816246** [comment]
Implemented password lock functionality for the configurations settings
Integrated backend to frontend code

- Modal popup for password inputs

![Image](https://user-images.githubusercontent.com/39515771/224553750-e7f137bb-3b0e-4f4b-9062-3a41611abbed.png)

![Image](https://user-images.githubusercontent.com/39515771/224553794-afe3585f-5ed8-4ee5-a7d1-744d02ba1b3c.png)

- Password functions

![Image](https://user-images.githubusercontent.com/39515771/224553854-15fc936b-4284-4631-a046-3c5f160824ef.png)

![Image](https://user-images.githubusercontent.com/39515771/224553898-18f8ae7b-00ca-44df-8a56-1ccaf3d3945a.png)
